/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpi_Prequest */

#ifndef _Included_mpi_Prequest
#define _Included_mpi_Prequest
#ifdef __cplusplus
extern "C" {
#endif
#undef mpi_Prequest_NULL
#define mpi_Prequest_NULL 0L
#undef mpi_Prequest_TYPE_NORMAL
#define mpi_Prequest_TYPE_NORMAL 0L
#undef mpi_Prequest_TYPE_OBJECT
#define mpi_Prequest_TYPE_OBJECT 1L
#undef mpi_Prequest_OP_SEND
#define mpi_Prequest_OP_SEND 0L
#undef mpi_Prequest_OP_RECV
#define mpi_Prequest_OP_RECV 1L
#undef mpi_Prequest_MODE_STANDARD
#define mpi_Prequest_MODE_STANDARD 0L
#undef mpi_Prequest_MODE_BUFFERED
#define mpi_Prequest_MODE_BUFFERED 1L
#undef mpi_Prequest_MODE_SYNCHRONOUS
#define mpi_Prequest_MODE_SYNCHRONOUS 2L
#undef mpi_Prequest_MODE_READY
#define mpi_Prequest_MODE_READY 3L
#ifdef __cplusplus
}
#endif
#endif
