#!/bin/sh

JAVASRC=../../lib/classes

CLASSPATH=${JAVASRC}

export CLASSPATH

CLASSPREFIX=mpjdev.

for i in Buffer WriteBuffer ObjectWriteBuffer ReadBuffer ObjectReadBuffer \
         Comm Request
do
  javah -jni ${CLASSPREFIX}$i
done

cp buff_typeDef.h mpjdev_Comm.h mpjdev_Request.h ../C

